import json
import boto3
import os
from datetime import datetime

sns_client = boto3.client('sns')
SNS_TOPIC_ARN = os.environ['SNS_TOPIC_ARN']

# Allowed root account actions (typically only account setup)
ALLOWED_ROOT_ACTIONS = [
    'GetAccountSummary',
    'GetServiceLastAccessedDetails',
    'ListAccountAliases'
]

def lambda_handler(event, context):
    """
    Detects root account usage
    """
    try:
        detail = event['detail']
        event_name = detail['eventName']
        user_identity = detail['userIdentity']
        source_ip = detail.get('sourceIPAddress', 'Unknown')

        # Validate root account activity
        detection = detect_root_usage(detail)

        if detection:
            alert = create_alert(detection, detail)
            send_alert(alert)

            return {
                'statusCode': 200,
                'body': json.dumps({'alert_sent': True, 'detection': detection['type']})
            }

        return {
            'statusCode': 200,
            'body': json.dumps({'alert_sent': False})
        }

    except Exception as e:
        print(f"Error processing event: {str(e)}")
        raise

def detect_root_usage(detail):
    """
    Detect suspicious root account usage
    """
    event_name = detail['eventName']
    user_identity = detail['userIdentity']

    # Skip allowed read-only actions
    if event_name in ALLOWED_ROOT_ACTIONS:
        return None

    # Root account should rarely be used
    if user_identity.get('type') == 'Root':
        # Escalate based on action severity
        severity = 'CRITICAL' if is_dangerous_action(event_name) else 'HIGH'

        return {
            'type': 'Root Account Activity Detected',
            'severity': severity,
            'technique': 'T1078.004',
            'tactic': 'Privilege Escalation / Persistence',
            'action': event_name,
            'mfa_used': detail.get('userIdentity', {}).get('invokedBy') == 'signin.amazonaws.com'
        }

    return None

def is_dangerous_action(event_name):
    """
    Check if action is particularly dangerous for root account
    """
    dangerous_actions = [
        'CreateAccessKey',
        'DeleteAccessKey',
        'PutUserPolicy',
        'AttachUserPolicy',
        'CreateUser',
        'DeleteUser',
        'ChangePassword',
        'DeactivateMFADevice',
        'DeleteAccountPasswordPolicy'
    ]
    return event_name in dangerous_actions

def create_alert(detection, detail):
    """
    Format alert message
    """
    user_identity = detail['userIdentity']
    source_ip = detail.get('sourceIPAddress', 'Unknown')
    user_agent = detail.get('userAgent', 'Unknown')

    alert = {
        'timestamp': datetime.utcnow().isoformat() + 'Z',
        'detection_type': detection['type'],
        'severity': detection['severity'],
        'mitre_attack': {
            'technique': detection['technique'],
            'tactic': detection['tactic']
        },
        'event_details': {
            'event_name': detail['eventName'],
            'event_time': detail['eventTime'],
            'source_ip': source_ip,
            'user_agent': user_agent,
            'mfa_used': detection.get('mfa_used', False)
        },
        'actor': {
            'type': 'Root',
            'arn': user_identity.get('arn', 'root'),
            'account_id': user_identity.get('accountId')
        },
        'recommendation': 'Root account should only be used for account setup. Use IAM users with least privilege instead.'
    }

    return alert

def send_alert(alert):
    """
    Send alert to SNS
    """
    subject = f"[{alert['severity']}] {alert['detection_type']}"

    message = f"""
AWS Threat Detection Alert

Detection: {alert['detection_type']}
Severity: {alert['severity']}
Timestamp: {alert['timestamp']}

MITRE ATT&CK:
  Technique: {alert['mitre_attack']['technique']}
  Tactic: {alert['mitre_attack']['tactic']}

Event Details:
  Event: {alert['event_details']['event_name']}
  Time: {alert['event_details']['event_time']}
  Source IP: {alert['event_details']['source_ip']}
  MFA Used: {alert['event_details']['mfa_used']}

Actor:
  Type: Root Account
  Account: {alert['actor']['account_id']}

Recommendation:
{alert['recommendation']}

---
This alert was generated by AWS Threat Detection Lab
"""

    sns_client.publish(
        TopicArn=SNS_TOPIC_ARN,
        Subject=subject,
        Message=message
    )

    print(f"Alert sent: {subject}")
